### PR TITLE
Add DSL discussion.

### PR DESCRIPTION
**Pull request by geo2a**
I hope that is relevant.

### CODE REVIEW

**Comment by snowleopard** [comment]
@geo2a Great, that's what I wanted. I'll add references to these DSLs/models later. I wonder whether we have space for a short example using `do`-notation...

**Comment by geo2a** [comment]
Lines 37-49 of [this](https://github.com/tuura/farfalle/blob/master/Microprogram.hs) file seem rather short and self-contained to me — it has all the goods: custom `Monad` with associated datatype and a `do`-notation example.

**Comment by snowleopard** [comment]
Agreed. If you manage to describe it clearly in a short paragraph, we can give it a try. (Putting everything in 2 pages is going to be a challenge.)

**Comment by geo2a** [comment]
Unfortunately, I don't have time right now, but I hope to be able to do it tomorrow.

**Pull request merged**
